#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_LinQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Northwind")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Datos_LinQ.Properties.Settings.Default.NorthwindConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vw_GestionOrdenesPorEmpleados> vw_GestionOrdenesPorEmpleados
		{
			get
			{
				return this.GetTable<vw_GestionOrdenesPorEmpleados>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_GestionOrdenesPorEmpleados")]
	public partial class vw_GestionOrdenesPorEmpleados
	{
		
		private System.Nullable<int> _añoOrden;
		
		private System.Nullable<int> _MesOrden;
		
		private System.Nullable<int> _DiaOrden;
		
		private string _NombreEmpleado;
		
		private System.Nullable<int> _Edad;
		
		private string _CompanyName;
		
		private string _Country;
		
		private string _ProductName;
		
		private string _CategoryName;
		
		private decimal _UnitPrice;
		
		private short _Quantity;
		
		private System.Nullable<decimal> _montoReacudado;
		
		public vw_GestionOrdenesPorEmpleados()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_añoOrden", DbType="Int")]
		public System.Nullable<int> añoOrden
		{
			get
			{
				return this._añoOrden;
			}
			set
			{
				if ((this._añoOrden != value))
				{
					this._añoOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesOrden", DbType="Int")]
		public System.Nullable<int> MesOrden
		{
			get
			{
				return this._MesOrden;
			}
			set
			{
				if ((this._MesOrden != value))
				{
					this._MesOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaOrden", DbType="Int")]
		public System.Nullable<int> DiaOrden
		{
			get
			{
				return this._DiaOrden;
			}
			set
			{
				if ((this._DiaOrden != value))
				{
					this._DiaOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEmpleado", DbType="NVarChar(31) NOT NULL", CanBeNull=false)]
		public string NombreEmpleado
		{
			get
			{
				return this._NombreEmpleado;
			}
			set
			{
				if ((this._NombreEmpleado != value))
				{
					this._NombreEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(15)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice", DbType="Money NOT NULL")]
		public decimal UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this._UnitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="SmallInt NOT NULL")]
		public short Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoReacudado", DbType="Money")]
		public System.Nullable<decimal> montoReacudado
		{
			get
			{
				return this._montoReacudado;
			}
			set
			{
				if ((this._montoReacudado != value))
				{
					this._montoReacudado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
