//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionUsuariosDatosEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente_Enfermedad
    {
        public int id { get; set; }
        public Nullable<int> id_Paciente { get; set; }
        public Nullable<int> id_Enfermedad { get; set; }
        public Nullable<System.DateTime> fechaEnfermedad { get; set; }
        public string observacion { get; set; }
    
        public virtual Enfermedad Enfermedad { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
